version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Clean.Architecture/Dockerfile
    ports:
      - 5252:5252
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "MyPass@word"
      ACCEPT_EULA: "Y"
      MSSQL_USER: "SA"